package com.jmlessous.entities;

public enum Role {
    ADMIN,
    CLIENT,
    CONSEILLERCLIENTELE,
    GESTIONNAIRECLIENTELE,
    MEMBREDIRECTOIRE,
    AGENTRH,
    AGENTMARKETING,
    FINANCIER,
    EMPLOYEASSURANCE
}
